name: Workflow Queue Runner

on:
  workflow_dispatch:
  schedule:
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'

jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Run Trigger Script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python trigger.py
