name: Runner

on:
  workflow_dispatch:
  schedule:
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'

concurrency:
  group: runner-queue
  cancel-in-progress: false

jobs:
  runner:
    runs-on: ubuntu-22.04
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      - name: Run Trigger Script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python trigger.py
