name: BHNS1 Epey Mybhianesse0

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5,7,12,17,22,27,32,37,42,47,52,57 * * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install unidecode

      # 🔐
      - name: Decode Python Script From Base64 Secret
        run: |
          echo "${{ secrets.EPEP_PY }}" | base64 -d > epep.py

      - name: Create Required Folders
        run: |
          mkdir -p a
          mkdir -p m3u_permanent

      - name: Run Script
        run: |
          python epep.py

      - name: Commit & Push Result
        run: |
          git config --global user.name "yanshdroid0[bot]"
          git config --global user.email "yanshdroid0[bot]@users.noreply.github.com"
          git add a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/live0.m3u
          git commit -m "🔄 Auto Update M3U $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
