name: BHNS0 Auto Run

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install aiohttp
        run: pip install aiohttp

      - name: Decode Script
        run: |
          echo "${{ secrets.EPE_PY }}" | base64 -d > epe.py

      - name: Run Script
        run: python3 epe.py

      - name: Commit Result
        run: |
          git config --global user.name "yanshdroid[bot]"
          git config --global user.email "yanshdroid[bot]@users.noreply.github.com"
          git add live.m3u
          git commit -m "🔄 Auto update live.m3u" || echo "No changes"
          git push
