name: bhns0 Auto Runepe

on:
  schedule:
    # Run every hour
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - main
    paths:
      - 'epe.py'
      - '.github/workflows/bhns0.yml'

jobs:
  merge-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install aiohttp
        run: pip install aiohttp

      - name: Decode Script
        run: |
          echo "${{ secrets.EPE_PY }}" | base64 -d > epe.py

      - name: Run Script
        run: python3 epe.py

      - name: Commit Result
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/live.m3u
          git commit -m "🔄 Auto update a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/live.m3u" || echo "No changes"
          git push
