name: Auto Mybhianesse0

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EPE_PY: ${{ secrets.EPE_PY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 🔥 
      - name: Create Python File From Secret
        run: |
          echo "$EPE_PY" > epe.py

      # 🔥 
      - name: Check Python File
        run: |
          ls -lah
          head -20 epe.py

      - name: Run Script
        run: python epe.py

      - name: Check Output
        run: |
          echo "=== FILE LIST ==="
          ls -lah
          if [ -f live.m3u ]; then
            echo "File created"
            head -20 live.m3u
          else
            echo "live.m3u NOT FOUND"
          fi

      - name: Commit & Push
        run: |
          git config --global user.name "yanshdroid[bot]"
          git config --global user.email "yanshdroid[bot]@users.noreply.github.com"

          if [ -f live.m3u ]; then
            git add live.m3u
            git commit -m "Auto update $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes"
            git push
          else
            echo "Nothing to commit"
          fi
