name: BHNS1 Epey Mybhianesse0

on:
  schedule:
    # Run every hour
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - main
    paths:
      - 'epep.py'
      - '.github/workflows/bhns1.yml'

jobs:
  merge-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install unidecode

      # 🔐
      - name: Decode Python Script From Base64 Secret
        run: |
          echo "${{ secrets.EPEP_PY }}" | base64 -d > epep.py

      - name: Create Required Folders
        run: |
          mkdir -p a
          mkdir -p m3u_permanent

      - name: Run Script
        run: |
          python epep.py

      - name: Commit & Push Result
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/live0.m3u
          git commit -m "🔄 Auto Update M3U $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
