name: Live ajga

on:
  schedule:
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'hh.py'
      - '.github/workflows/hh.yml'

jobs:
  merge-and-commit:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Create Python Script From Base64 Secret
        run: |
          echo "${{ secrets.HH_PY }}" | base64 -d > hh.py

      - name: Run Script
        run: python hh.py

      - name: Commit Playlist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "yanshdroid[bot]"
          git config --global user.email "yanshdroid[bot]@users.noreply.github.com"

          git add a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/live.php

          git commit -m "Auto Update $(date)" || echo "No changes"

          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
