name: Lviptf

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main

# tidak membatalkan runner lain
concurrency:
  group: playlist
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Restore Python script from secret
        run: |
          echo "${{ secrets.II_PY }}" | base64 -d > ii.py
          chmod +x ii.py

      - name: Run scraper
        run: |
          python ii.py
          ls -lah

      - name: Commit playlist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FILE="a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/live3.php"

          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          if [ -f "$FILE" ]; then
            git add "$FILE"
            git commit -m "update playlist $(date)" || echo "No changes"

            # retry push jika banyak runner
            for i in 1 2 3 4 5 6
            do
              git pull --rebase --autostash origin main
              git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main && break
              echo "Push failed, retry $i..."
              sleep 5
            done
          else
            echo "live3.php not found"
          fi
