name: CL KK

on:
  schedule:
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/kk.yml'

jobs:
  merge-and-commit:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Decode Python Script
        run: |
          echo "${{ secrets.KK_PY }}" | base64 -d > kk.py
          chmod +x kk.py

      - name: Run scraper
        run: |
          python kk.py

      - name: Commit playlist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FILE="a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/live2.php"

          git config --global user.name "yanshdroid[bot]"
          git config --global user.email "yanshdroid[bot]@users.noreply.github.com"

          if [ -f "$FILE" ]; then
            git add "$FILE"
            git commit -m "Auto update playlist $(date)" || echo "No changes"

            # retry push untuk multi runner
            for i in 1 2 3 4 5 6
            do
              git pull --rebase --autostash origin main
              git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main && break
              echo "Push failed. retry $i..."
              sleep 5
            done

          else
            echo "live2.php not found"
          fi
