name: lve epe

on:
  schedule:
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'epe.py'
      - '.github/workflows/lve.yml'

# mencegah workflow bentrok
concurrency:
  group: playlist-generator
  cancel-in-progress: true

jobs:
  merge-and-commit:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp

      - name: Decode Script
        run: |
          echo "${{ secrets.EPE_PY }}" | base64 -d > epe.py
          chmod +x epe.py

      - name: Create Folder Path
        run: |
          mkdir -p a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z

      - name: Run Script
        run: |
          python3 epe.py

      - name: Commit Result
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FILE="a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/live.m3u"

          git config --local user.name "yanshdroid[bot]"
          git config --local user.email "yanshdroid[bot]@users.noreply.github.com"

          if [ -f "$FILE" ]; then
            git add "$FILE"
            git commit -m "🔄 Auto update $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes"

            # retry push jika repo berubah
            for i in 1 2 3 4 5
            do
              git pull --rebase origin main
              git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git && break
              echo "Push failed. Retry $i..."
              sleep 3
            done
          else
            echo "live.m3u not found"
          fi
