name: Get Premium

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # penting supaya bisa push

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 📦 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pip install aiohttp

      - name: 🔐 Decode Script
        run: |
          echo "${{ secrets.PREMIUM_PY_B64 }}" | base64 -d > premium.py
          chmod +x premium.py

      - name: ▶️ Run Script
        run: python premium.py

      - name: 📤 Commit M3U
        run: |
          git config --local user.email "yanshdroid2[bot]@users.noreply.github.com"
          git config --local user.name "yanshdroid2[bot]"

          if [ -f a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/live2.m3u ]; then
            git add a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/live2.m3u
            git diff --quiet && git diff --staged --quiet || git commit -m "Auto Update Premium M3U"
            git push
          else
            echo "a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/live2.m3u not found, skipping commit"
          fi
