name: Get Premium

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'premium.py'
      - '.github/workflows/premium.yml'

# mencegah workflow jalan bersamaan
concurrency:
  group: premium-m3u
  cancel-in-progress: true

jobs:
  merge-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      PREMIUM_PY_B64: ${{ secrets.PREMIUM_PY_B64 }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Create Folder Path
        run: |
          mkdir -p a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z

      - name: Decode Python Script
        run: |
          echo "$PREMIUM_PY_B64" | base64 -d > premium.py
          chmod +x premium.py

      - name: Run Script
        run: |
          python premium.py

      - name: Commit M3U
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          FILE="a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/live2.m3u"

          if [ -f "$FILE" ]; then
            git add "$FILE"
            git commit -m "Auto Update Premium M3U" || echo "No changes"

            # ambil update repo dulu
            git pull --rebase origin main

            # push
            git push
          else
            echo "M3U file not found"
          fi
