name: Delete Workflow Runs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Delete workflow runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          echo "Getting workflow runs..."

          runs=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
          https://api.github.com/repos/$OWNER/$REPO/actions/runs?per_page=100 \
          | jq '.workflow_runs[].id')

          for run_id in $runs
          do
            echo "Deleting run $run_id"

            curl -s -X DELETE \
              -H "Authorization: Bearer $GH_TOKEN" \
              https://api.github.com/repos/$OWNER/$REPO/actions/runs/$run_id
          done
