name: workflow-trigger

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'epe.py'
      - '.github/workflows/xiss.yml'

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Run Script
        env:
          TRIGGER_PY: ${{ secrets.TRIGGER_PY }}
        run: python trigger.py
